
services:
  # Backend service
  - type: web
    name: ocr-engine-backend
    rootDir: Backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: "False"  # String value for environment variable
      - key: DJANGO_SECRET_KEY  # For Django
        generateValue: true
      - key: SECRET_KEY  # For FastAPI
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://ocr-engine-frontend.onrender.com"
      - key: FRONTEND_URL  # Important for activation links
        value: "https://ocr-engine-frontend.onrender.com"
      - key: X_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ocr-engine-db
          property: connectionString

  # Frontend service
  - type: web
    name: ocr-engine-frontend
    rootDir: frontend
    env: static
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://ocr-engine-backend.onrender.com"

# Database configuration
databases:
  - name: ocr-engine-db
    databaseName: ocr_engine
    user: ocr_engine_user

