services:
  #  backend-only service
  - type: web
    name: ocr-software-backend
    env: docker
    dockerfilePath: ./Backend/Dockerfile
    dockerContext: ./
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY  # For FastAPI
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "ocr-software-62gw.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        # Include local frontend URL
        value: "https://ocr-software-62gw.onrender.com,http://localhost:3000"
      - key: PORT
        value: "10000"  
      - key: X_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ocr-engine-db
          property: connectionString

# Database configuration
databases:
  - name: ocr-engine-db
    databaseName: ocr_engine
    user: ocr_engine_user
